[env]
TERM = "xterm-256color"

[font]
size = 11.0
# size = 10.0
builtin_box_drawing = true


[font.glyph_offset]
# y = 1
y = 2
# x = 1

[font.normal]
# family = "FantasqueSansM Nerd Font"
family = "DepartureMono Nerd Font"
# family = "CommitMono Nerd Font"
# family = "DMMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "MonaspiceNe NF"
style = "Regular"
# style = "Medium"

[font.bold]
# family = "FantasqueSansM Nerd Font"
# family = "CommitMono Nerd Font"
# family = "DMMono Nerd Font"
# family = "MonaspiceNe NF"
# style = "Bold"
style = "Regular"

[font.offset]
y = 5
# x = 1

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Shift|Alt"

[scrolling]
history = 10000

[terminal.shell]
program = "/bin/fish"

[window]
dynamic_title = true
opacity = 0.98
# opacity = 1

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
# import = ["~/.config/alacritty/themes/rose-pine-dawn.toml"]
# import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[terminal]

[mouse]
hide_when_typing = true
