
# [colors.primary]
# foreground = "#e0def4"
# background = "#232136"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"

# [colors.cursor]
# text = "#e0def4"
# cursor = "#56526e"

# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#56526e"

# [colors.search.matches]
# foreground = "#908caa"
# background = "#393552"

# [colors.search.focused_match]
# foreground = "#232136"
# background = "#ea9a97"

# [colors.hints.start]
# foreground = "#908caa"
# background = "#2a273f"

# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#2a273f"

# [colors.line_indicator]
# foreground = "None"
# background = "None"

# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#2a273f"

# [colors.selection]
# text = "#e0def4"
# background = "#44415a"

# [colors.normal]
# black = "#393552"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"

# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"

# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"

[font]
size = 10.0
builtin_box_drawing = true

[font.bold]
family = "MonaspiceNe NF"
style = "Bold"

[font.glyph_offset]
y = 1

[font.normal]
family = "MonaspiceNe NF"
style = "Medium"

[font.offset]
y = 4

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Shift|Alt"

[scrolling]
history = 10000

[terminal.shell]
program = "/bin/fish"

[window]
dynamic_title = true
# opacity = 0.95
opacity = 1

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
# import = ["~/.config/alacritty/rose-pine-dawn.toml"]
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[terminal]

[mouse]
hide_when_typing = true
