spacing         = 2
padding         = 0
hide_ascii      = false
prefer_small_ascii = true
separator       = ""
key_color       = "Blue"
separator_color = "White"

[palette]
type = "Full"
visible = true

[bar]
glyph           = "ß‹"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
border          = "plain"
visible         = false

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "host"
kernel          = "kernel"
battery         = "battery"
os              = "os"
de              = "de"
wm              = "wm"
distro          = "distro"
terminal        = "term"
shell           = "shell"
packages        = "pkgs"
uptime          = "up"
memory          = "mem"
machine         = "machine"
local_ip        = "ip"
backlight       = "brightness"
resolution      = "resolution"
cpu_load        = "cpu%"
cpu             = "cpu"

[custom_ascii]
path="~/.config/macchina/ascii"
color = "Cyan"
