#! /bin/sh

wmname LG3D
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
nm-applet &
nitrogen --restore &
picom &
dunst &
birdtray &
caffeine &
setxkbmap -option caps:escape &
xset r rate 400 40 &
unclutter --timeout 1 --jitter 50 --ignore-scrolling &
rclone mount syncraft_at_google:/ /home/himon/Remote/syncraft@google/ --vfs-cache-mode full --daemon

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 3
bspc config window_gap 20
bspc config top_padding 36

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a "microsoft teams - preview" desktop='^10'
bspc rule -a "Microsoft Teams - Preview" desktop='^10'
bspc rule -a "Mail" desktop='^9'
bspc rule -a "Thunderbird" desktop='^9'
bspc rule -a "GG" desktop='^8'
bspc rule -a "Gg" desktop='^8'
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#312e39"
bspc config active_border_color "#312e39"
bspc config focused_border_color "#3e518e"
bspc config presel_feedback_color "#312e39"
bspc config presel_feedback true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config pointer_action2 resize_side
